"""Add many-to-many relationship between Schedule and Load models

Revision ID: 2713f4564ff6
Revises: 7035f38beb0a
Create Date: 2023-11-06 00:28:12.886421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2713f4564ff6'
down_revision = '7035f38beb0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_load',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('schedule_id', 'load_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_load')
    # ### end Alembic commands ###
