"""Add Load TimeIntervall

Revision ID: 52d47d500ff9
Revises: f19b52ede2d5
Create Date: 2023-11-05 23:36:48.189394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d47d500ff9'
down_revision = 'f19b52ede2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('load_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['load.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_interval')
    # ### end Alembic commands ###
