"""Changed time columns to datetime

Revision ID: 9da290906053
Revises: 2713f4564ff6
Create Date: 2023-11-06 22:35:56.791565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9da290906053'
down_revision = '2713f4564ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    ALTER TABLE schedule 
    ALTER COLUMN start_time TYPE TIMESTAMP WITHOUT TIME ZONE 
    USING '1970-01-01'::date + start_time::time
    ''')
    op.execute('''
    ALTER TABLE schedule 
    ALTER COLUMN end_time TYPE TIMESTAMP WITHOUT TIME ZONE 
    USING '1970-01-01'::date + end_time::time
    ''')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
