"""Add Load, DutyCycle, and Project models

Revision ID: f19b52ede2d5
Revises: 7856785a77a6
Create Date: 2023-11-05 13:19:38.452587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19b52ede2d5'
down_revision = '7856785a77a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duty_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('duty_cycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duty_cycle_id'], ['duty_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('load')
    op.drop_table('duty_cycle')
    op.drop_table('project')
    # ### end Alembic commands ###
